app:
  log_level: debug
  log_style: human
  metrics:
    addr: localhost:5191
    user: test
    password: password

oscar:
  addr: 0.0.0.0:5190
  bos: 10.0.1.29:5190

db:
  name: postgres
  user: postgres
  password: password
  host: localhost
  port: 5432
  ssl_mode: disable
